export const generalSourceText = `
    The sun was shining brightly in the sky. Birds were chirping and flying around. Children were playing in the park and having fun. It was a beautiful day.
    Jane walked to the store to buy some groceries. She needed milk, bread, and eggs for breakfast. The store was busy but she found everything she needed quickly. She paid for her groceries and walked back home. A zebra and extra jeeps. 
    
    Markov chains are a simple way to generate text that looks like it was written by humans. To use Markov chains, we need to have a lot of similar documents. Simple Markov chains are the building blocks of other, more advanced techniques.

    To generate text with Markov chains, we need to decide what our states will be and what probabilities we will assign to jumping from one state to another. We can use a character-based model or a word-based model. In a character-based model, we define our state as the last n characters weve seen and try to predict the next one. In a word-based model, we define our state as the last n words weve seen and try to predict the next one. We can choose which type of model to use.
    
    I live in a house near the mountains. I have two brothers and one sister, and I was born last. My father teaches mathematics, and my mother is a nurse at a big hospital. My brothers are very smart and work hard in school. My sister is a nervous girl, but she is very kind. My grandmother also lives with us. She came from Italy when I was two years old. She has grown old, but she is still very strong. She cooks the best food!

    My family is very important to me. We do lots of things together. My brothers and I like to go on long walks in the mountains. My sister likes to cook with my grandmother. On the weekends we all play board games together. We laugh and always have a good time. I love my family very much.

    I just returned from the greatest summer vacation! It was so fantastic, I never wanted it to end. I spent eight days in Paris, France. My best friends, Henry and Steve, went with me. We had a beautiful hotel room in the Latin Quarter, and it wasnt even expensive. We had a balcony with a wonderful view.

    We visited many famous tourist places. My favorite was the Louvre, a well-known museum. I was always interested in art, so that was a special treat for me. The museum is so huge, you could spend weeks there. Henry got tired walking around the museum and said “Enough! I need to take a break and rest.”

    We took lots of breaks and sat in cafes along the river Seine. The French food we ate was delicious. The wines were tasty, too. Steves favorite part of the vacation was the hotel breakfast. He said he would be happy if he could eat croissants like those forever. We had so much fun that were already talking about our next vacation.
`;


/***
 * As the name suggests, these are source text for each letter of the alphabet. The usecase for these is simple:
 * When a user starts a game, the source text for them will be generated by coupling together the general source text + the source text of their weakest alphabet.
 */

export const letterDominantSourceTexts: { [key: string]: string } = {
    'a': 'banana cabana Alaska drama pajama llama safari mascara algebra algebraic anaconda anaesthesia Australia macadamia papaya propaganda aquamarine aromatherapy abracadabra barracuda cassava caramelized',

    'b': 'bubble rubble hobble crabby blubber blobby bulb bumblebee abbot abominable abacus abhorrent abbot ribbit cabby caboodle cabernet adobe barbie barbiturate barbell barbwire barbeque barnacle',

    'c': 'Academic acrobatics arctic calculus cascade catastrophe chalice chicory circus classic coconut concoction concomitant cornucopia crackerjack critical crucifixion cursive cyclical cyclist cynic', 

    'd': 'Deadline downward added dashboard drudgery oddball dud deductible diddly dandy doodad hoodie doodle didgeridoo dado drowsy dandruff decadent duvet doormat drizzle doodah dashboard doodler',

    'e': 'secede embezzle celery telescope three-degree pedigree leveler telescope gender theme jester leopard perceptive selectee beetleweed emerald veneer severe preemie serpentene percentage emeritus egregious cemented esoteric',

    'f': 'Fluff off fluffy offer different effect coffee cliff staff stuff life deaf benefit brief future safety feature effort preference flavor define shift forge buffalo beef',

    'g': 'giggle garbage goal glaze goggles groovy gravity game ghost gift guitar gigabyte green gem giant glass grape glue gown gossip glance goatee grit groove grill',

    'h': 'happy helmet hello hammer heart heavy hot house honey hair hamburger harmony hope hike horizon hat hawk heaven heater hinge hive hoodie heel history hum',

    'i': 'inside imagine interesting idea item ice important inspire include impossible ignite identify ink iguana intense iron illegal improve island icing innocent income indicate inspire invitation',

    'j': 'jump job juice jelly jacket joke jazz join juggle journal journey jeans jolt jungle judge joy jewel jam jet jockey jackpot juggernaut junior just jinx',

    'k': 'king keep kind kitchen key kite kick kitten kangaroo knife knowledge kid kiss kernel kilogram knit kettle keyboard knight kayak koala kernel karma kickback keep',

    'l': 'love life laughter lemon light lucky lion line lemonade lamb ladybug letter learn library long leg lizard lake lock loaf lipstick lamp loud ladder low',

    'm': 'music moon mountain move magic machine meadow map milk memory movie maze melody morning muffin money marble monster marshmallow match mittens mirror moose mushroom mouse',

    'n': 'night nature nose nest never nut noodle nurse nap nickel new napkin name note needle neon nephew necklace number naptime navy nook north notebook nose',

    'o': 'orange ocean oven octopus onion owl orbit oil oak oasis oyster office opera omelette odor oboe otter oceanic offer opinion occasion obstacle obsession opportunity outside',

    'p': 'pizza party puppy pen paper purple pear pencil popcorn photo pumpkin pig plane paint pool pillow plate penguin piano park pan polo pond peach pepper',

    'q': 'quick quiet quiz quote quack queen question quarter quilt queue quiver quirky quad quality quench quest quake quaint quip quail quay quintet quantum quinoa qualified',

    'r': 'rabbit run rainbow road rose ring river rock red robot room rug rain raccoon raspberry radio ruler rust round ribbon ranch ride rooster recycle race',

    's': 'sun star sea snake sand surf sky sock spoon snow slide smile strawberry sailboat soccer sugar scissors shrimp street sandal suitcase sandwich school snail sofa',

    't': 'table top temple tooth telephone track tennis treasure trip tent trumpet tornado toast turkey tangerine tackle tango target tonic trampoline twig trolley tuxedo turmeric twinkle',

    'u': 'umbrella uniform universe unique utensil uncle upbeat urge up use upper umpire unity underwear university ultra urban udder ugly universe universe undulate unicorn user utility upright',

    'v': 'vacation volcano violet vacuum vase van vest vegetable violin village vampire victory voice video velvet vine vase vehicle view volleyball variety verse vase vulture value',

    'w': 'water whale wind watch wheat wagon window wood witch winter wine wallet walk waiter watermelon whisper wedge wrist waffle wrench wardrobe wonder wavy wire wish',

    'x': 'xylophone xray extra exhaust execute exude examine exact exotic expert exhale expand exclaim exist exile express extinguish exuberant extensive exit exterior exquisite extravagant explanation exhibit',

    'y': 'yellow yogurt yawn year yacht yarn yard yesterday yo-yo yield yam yodel yam yellowish yippee yeast youth yoke yummy yoga yule yearbook yawn young yourself',

    'z': 'zebra zoo zero zigzag zipper zinc zodiac zone zest zucchini zenith zany zap zealot zeppelin zephyr zenith zebra zookeeper zombie zoom zipper zing zig zonal'
}

